---
- name: Setup local user with SSH key and sudo access
  hosts: all
  become: yes

  vars:
    new_username: topflight_management
    ssh_public_key_file: id_rsa.pub
    sudo_group: sudo

  tasks:
    - name: Ensure the new user exists
      ansible.builtin.user:
        name: "{{ new_username }}"
        state: present
        shell: /bin/bash
        create_home: yes

    - name: Ensure .ssh directory exists in the user's home
      ansible.builtin.file:
        path: "/home/{{ new_username }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ new_username }}"
        group: "{{ new_username }}"

    - name: Copy the public key to authorized_keys
      ansible.builtin.copy:
        src: "/static/files/{{ ssh_public_key_file }}"
        dest: "/home/{{ new_username }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ new_username }}"
        group: "{{ new_username }}"

    - name: Add the new user to the sudo group (which grants sudoers access)
      ansible.builtin.user:
        name: "{{ new_username }}"
        groups: "{{ sudo_group }}"
        append: yes
