---
- name: Update Ubuntu and reboot if required
  hosts: all
  become: true
  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_result

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system if required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists

    - name: Ensure the system is back online
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
